<head>
    <meta charset = "utf-8"/>
    <meta name = "description" content = "Blade EduNET Comapny Website"/>
    <meta name = "keywords" content = "job application, education, work, development"/>
    <meta name = "author" content = "Blake, Marcus, Aaron"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Blade EduNET </title>
    <link href = "Styles/Style.css" rel = "stylesheet"/>
</head>
<body>
    <div class = "BackgroundContainer">
    <header>
        <img src = "Images/Nav_Logo.png" alt = "Blade EduNET Logo">
        <h1> Blade EduNET </h1> <!--centre align h1-->
        <nav>
            <a href = "index.html">Home Page</a>
            <a href = "jobs.html">Available Positions</a>
            <a href = "apply.html">Job Application</a>
            <a href = "software.html">Our Software</a>
            <a href = "about.html">About Us</a>
        </nav>
    </header>